source:
  type: cardano_net
  relay: 
    - relays-new.cardano-mainnet.iohk.io
    - 3001
      # - preview-node.world.dev.cardano.org
      # - 30002
      # - preprod-node.world.dev.cardano.org
      # - 30000

sink:
  type: cardano
  db:
    type: postgres
    host: localhost
    port: 5455
    user: carp
    password: "1234"
    db: carp_mainnet
  network: preprod

start_block:
