[alias]
migrate = "run --manifest-path ./migration/Cargo.toml --"
rollback = "run --manifest-path ./rollback/Cargo.toml --"
reparse = "run --manifest-path ./reparse/Cargo.toml --"
plan-visualizer = "run --manifest-path ./plan-visualizer/Cargo.toml --"