[ByronBlockTask]
readonly=true

[ByronTransactionTask]
readonly=true

[MultieraBlockTask]
readonly=true

[MultieraTransactionTask]
readonly=true

[MultieraMetadataTask]
readonly=true

[MultieraAssetMintTask]

[MultieraCip25EntryTask]
