[GenesisBlockTask]
include_payload=false

[GenesisTransactionTask]
include_payload=false

[ByronBlockTask]
readonly=false
include_payload=false

[ByronTransactionTask]
readonly=false
include_payload=false

[ByronAddressTask]

[ByronOutputTask]

[ByronInputTask]

[MultieraBlockTask]
readonly=true
include_payload=false

[MultieraTransactionTask]
readonly=true
include_payload=false

[MultieraMetadataTask]
readonly=false

[MultieraAssetMintTask]
readonly=true

[MultieraCip25EntryTask]
