source:
  type: cardano_net
  relay:
    - 172.20.0.4
    - 3001
      # - relays-new.cardano-mainnet.iohk.io
      # - 3001
      # - preview-node.world.dev.cardano.org
      # - 30002
      # - preprod-node.world.dev.cardano.org
      # - 30000

sink:
  type: cardano
  db:
    type: postgres
    database_url: postgresql://carp:1234@postgres:5432/carp_preprod
  network: preprod # preview / mainnet / testnet

start_block:
