name: Build carp & carp webserver


on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    uses: dcSpark/carp/.github/workflows/build-workflow.yml@main
    with:
      REGISTRY: dcspark
      REPOSITORY_CARP: carp
      REPOSITORY_CARP_WEBSERVER: carp-webserver
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
