name: Test documentation

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: "Compile documentation"
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: "-Dwarnings"
        with:
          command: doc
          args: --manifest-path=indexer/Cargo.toml --no-deps
