source:
  type: oura
  socket: "relays-new.cardano-mainnet.iohk.io:3001"
  bearer: Tcp # Unix

sink:
  type: cardano
  db:
    type: postgres
    database_url: postgresql://carp:1234@localhost:5432/carp_mainnet
  network: mainnet # preview / preprod / testnet / custom

start_block:
